### ISSUE TITLE
State machine - Taxiing back to gate

### ISSUE THREAD

**Issue by ptsmonteiro** [xairline/zon#18]
State machine should support:
- [x] engine start->taxi out->engine stop (flight is discarded)
- [x] engine start->taxi out->take off roll (RTO)->taxi->engine stop
- [x] engine start->taxi out->take off roll (RTO) -> taxi -> take off roll -> ... normal flight

Essentially, we have to check, for each state, what are all the possible transitions.

**Comment by zodiac1214** [comment]
engine start->taxi out->take off roll (RTO) -> taxi -> take off roll -> ... normal flight

is it true that if you reject takeoff you always have to go back and shutdown engine? Ask because i have two states for taxi: taxi out and taxi in. after RTO, the state can only go to taxi in right now....

@ptsmonteiro

**Comment by ptsmonteiro** [comment]
In reality you can to an RTO and then just taxi back to the runway and takeoff again. Or you can also go back to the gate.
Having that in mind, I think we should only have one taxi phase, not taxi in and out.
